
services:
  db:
    image: mariadb:10.6.17
    environment:
      MARIADB_ROOT_PASSWORD: abc123!
      MARIADB_DATABASE: fastapi
      MARIADB_USER: fauser
      MARIADB_PASSWORD: abc123!
    ports:
    - 3306:3306
    volumes:
    - md_data:/var/lib/mysql
    - ./db:/docker-entrypoint-initdb.d

  mariadb_exporter:
    image: quay.io/prometheuscommunity/mysqld-exporter
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME="root:abc123!@(db:3306)/
    depends_on:
      - db

  web:
    image: yunsung22/fawebapp
    build: web
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_USER: fauser
      DB_PASSWORD: abc123!
      DB_NAME: fastapi
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  md_data: